### ISSUE TITLE
[fuzzer] Status for Fuzzer Integration

### ISSUE THREAD

**Issue by yannicnoller** [squaresLab/security-repair-benchmarks#25]
I use this issue to track the status of the fuzzer integration.

## TODOs
- [X] Generate inputs in our environment for test `cve_2016_5314`
- [x] Include fuzzer reliably in the environment
	- [X] fix python package installations with PYTHONPATH
 	- [X] fix other installations with PATH
 	- [X] provide wrapper for fuzz.py
 	- [X] include fuzzer volume in secbugs container (not sure exactly, see below)
- [ ] Integrate fuzzer in patch validation and ranking algorithm. Chris wanted to fill in the control code and the instrumentation of the patched program.
- [ ] Provide configuration files (`config.ini`) and binary compilation for all subjects (expected to need a recompilation for each fuzzing campaign because of different parameters)
- [X] libtiff
	- [X] bugzilla_2611 (store all inputs)
	- [X] bugzilla_2633
	- [X] cve_2016_3186
	- [X] cve_2016_5314
	- [X] cve_2016_5321
	- [X] cve_2016_9273
	- [X] cve_2016_9532
	- [X] cve_2016_10092
	- [X] cve_2016_10094
	- [X] cve_2016_10272
	- [X] cve_2017_5225
	- [X] cve_2017_7595 (store all inputs)
	- [X] cve_2017_7599 (store all inputs)
	- [X] cve_2017_7600 (store all inputs)
	- [X] cve_2017_7601
- [X] binutils
	- [X] cve_2017_6965
	- [X] cve_2017_14745
	- [X] cve_2017_15020
	- [X] cve_2017_15025 (store all inputs)
- [x] coreutils
	- [X] gnubug_19784 (store all inputs)
	- [X] gnubug_25003 (store all inputs)
	- [X] gnubug_25023 (store all inputs)
	- [X] gnubug_26545 (store all inputs)
- [ ] ffmpeg (see #23)
	- [ ] bugchrom_1404 **TODO**
	- [ ] cve_2017_9992 **TODO**
- [x] jasper
	- [X] cve_2016_8691 (store all inputs)
	- [X] cve_2016_9557 (store all inputs)
- [X] libarchive
	- [X] cve_2016_5844 (store all inputs, combination_num=1)
- [x] libjpeg
	- [X] cve_2012_2806 (store all inputs)
	- [X] cve_2017_15232
	- [X] cve_2018_14498
	- [X] cve_2018_19664 (store all inputs)
- [X] libming
	- [X] cve_2016_9264
	- [X] cve_2018_8806
	- [X] cve_2018_8964
- [X] libxml2
	- [X] cve_2012_5134
	- [X] cve_2016_1838
	- [X] cve_2016_1839 (combination_num=1)
	- [X] cve_2017_5969
- [X] potrace
	- [X] cve_2013_7437 (store all inputs, combination_num=1)
- [X] zziplib
	- [X] cve_2017_5974
	- [X] cve_2017_5975
	- [X] cve_2017_5976
